services:
  db:
    image: postgres:17.5-alpine
    restart: no
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: TechFood
    profiles:
      - dev
      - prod
      - db

  adminer:
    image: adminer
    restart: no
    ports:
      - "8089:8080"
    profiles:
      - dev
      - db

  rabbitmq:
    image: 'rabbitmq:3.13-management-alpine'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=root'
      - 'RABBITMQ_DEFAULT_USER=root'
    ports:
      - "5672:5672"
      - "15672:15672"
    profiles:
      - dev
      - prod