spring.application.name=v2i-processing
server.port=8001

# Upload
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:v2i}}
spring.datasource.username=${POSTGRES_USER:root}
spring.datasource.password=${POSTGRES_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Queue
spring.rabbitmq.host=host.minikube.internal
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER:root}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:root}

# AWS
#aws.region=us-east-1
#aws.access-key-id=${AWS_ACCESS_KEY_ID}
#aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}
#aws.s3.bucket-name=${AWS_BUCKET_NAME}

#Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.health.db.enabled=true

# Gateway routes
v2i.web.url=${ORDER_SERVICE_URL:http://localhost:8000}
